buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/maven' }
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7.+'
    }
}

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.76'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'net.neoforged.moddev'

    println "Setup: ${project.name}";

    version = "${minecraft_version}-${mod_version}"

    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = uri('https://maven.neoforged.net/')}
    }

    neoForge {
        version = project.neo_version

        parchment {
            mappingsVersion = project.parchment_mappings_version
            minecraftVersion = project.parchment_minecraft_version
        }

        accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

        runs {
            client {
                client()
            }
        }

        mods {
            // define mod <-> source bindings
            // these are used to tell the game which sources are for which mod
            // mostly optional in a single mod project
            // but multi mod projects should define one per mod
            "${mod_id}" {
                sourceSet(sourceSets.main)
            }
        }
    }

    sourceSets.main.resources { srcDir 'src/generated/resources' }

    configurations {
        runtimeClasspath.extendsFrom localRuntime

    }

    jar {
        manifest {
            attributes([
                    "Specification-Title"     : "${project.name}",
                    "Specification-Vendor"    : "ModcraftMC",
                    "Specification-Version"   : "${mod_version}",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : "ModcraftMC",
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            ])
        }

        //rename 'mixin.refmap.json', 'datasync.mixin-refmap.json'
    }

//    if(project.name == 'cross-server-core'){
//        tasks.register('apiJar', Jar) {
//            archiveClassifier.set('api')
//            include '**/api/**'
//            from sourceSets.main.allSource
//            from sourceSets.main.output
//        }
//
//        tasks.register('sourcesJar', Jar) {
//            archiveClassifier.set('sources')
//            from sourceSets.main.allJava
//        }
//
//        artifacts {
//            archives apiJar
//            archives sourcesJar
//        }
//    }
}