group = 'fr.modcraftmc'
if(project.release_type == "snapshot") {
    version = "${minecraft_version}-${mod_version}-SNAPSHOT"
} else{
    version = "${minecraft_version}-${mod_version}"
}

configurations {
    // Create the library configuration, where our non-mod libraries will be added to
    library
    // Any dependency in the library configuration will also be added to the implementation configuration
    implementation.extendsFrom library

    shade
    library.extendsFrom shade
}

dependencies {
    jarJar(implementation(group: 'com.rabbitmq', name: 'amqp-client', version: '[5.16.0,)'))
    jarJar(implementation(group: 'org.mongodb', name: 'mongodb-driver-sync', version: '[5.3.0,)'))

    // include all transitive dependencies of mongodb-driver-sync
    jarJar(group: 'org.mongodb', name:'mongodb-driver-core', version: '[5.3.0,)')
    jarJar(group: 'org.mongodb', name:'bson', version: '[5.3.0,)')

    jarJar(implementation(group: 'com.moandjiezana.toml', name: 'toml4j', version: '[0.7.0,)'))
}

tasks.register('apiJar', Jar) {
    archiveClassifier.set('api')
    include '**/api/**'
    from sourceSets.main.allSource
    from sourceSets.main.output
}

tasks.register('sourcesJar', Jar) {
    archiveClassifier.set('sources')
    from sourceSets.main.allJava
}

jar{
    archiveBaseName = "${project.name}"
    if(project.release_type == "snapshot") {
        archiveVersion = "${minecraft_version}-${mod_version}-SNAPSHOT"
    } else{
        archiveVersion = "${minecraft_version}-${mod_version}"
    }
}

artifacts {
    archives apiJar
    archives sourcesJar
}

//jar.finalizedBy('shadowJar')


publishing {
    repositories {
        maven {
            name = "ModcraftMaven"
            if(project.release_type == "snapshot") {
                url = "https://maven.modcraftmc.fr/snapshots"
            } else{
                url = "https://maven.modcraftmc.fr/releases"
            }
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        crossServerCore(MavenPublication) { publication ->
            project.shadow.component(publication)

            groupId = "fr.modcraftmc"
            artifactId = "cross-server-core"
            version = project.mod_version

            artifact sourcesJar{
                archiveClassifier.set('sources')
            }
            artifact apiJar {
                archiveClassifier.set('api')
            }
        }
    }
}